# Simple workflow for testing mkdocs build
name: Test building TLP:CLEAR content

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - name: install mkdocs
        run: pip install -r requirements.txt
      - name: run mdformat
        run: mdformat --no-validate . && mdformat .
      - name: build site
        run:  python -m mkdocs build --strict
